# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "kibank"
version = "0.1.0"
authors = ["Sheldon Young <sheldon@softdev.ca>"]
description = "Tool for Kilohearts banks"
license = "Apache-2.0"
homepage = "https://github.com/softdevca/kibank"
repository = "https://github.com/softdev.ca/kibank"
documentation = "https://docs.rs/kibank"
keywords = ["cli", "audio", "synth", "presets"]

edition = "2021"
rust-version = "1.61"
publish = true

[features]
default = ["application"]

# Require for the command line interface. Should be disabled when depending on
# this crate as a library. For example, to use as a library in a Cargo.toml:
# `kibank = { version = "...", default-features = false }`
application = ["anyhow", "clap", "os_str_bytes", "walkdir"]

[dependencies]
anyhow = { version = "1.0.58", optional = true }
byteorder = "1.4.3"
clap = { version = "3.2", optional = true, default-features = false, features = ["std", "cargo", "color", "env", "suggestions", "wrap_help"] }
log = "0.4.17"
os_str_bytes = { version = "6.1.0", optional = true }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
simplelog = "0.12.0"
walkdir = { version = "2.3.2", optional = true }

[dev-dependencies]
assert_cmd = "2.0"
assert_fs = "1.0"
predicates = "2.1"

[package.metadata.docs.rs]
# Pass `--no-default-features` to Cargo on docs.rs
no-default-features = true
